# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 08:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=50)),
                ('process_name', models.CharField(default='', max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('period', models.IntegerField(default=1, help_text='period between updates in seconds')),
                ('account', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.FloatField(default=0)),
                ('month_k', models.FloatField(default=1, help_text='positive greater in winter')),
                ('hour_k', models.FloatField(default=1, help_text='positive greater in daytime')),
                ('longwave_k', models.FloatField(default=10000, help_text='positive integer large number longer wave')),
                ('longwave_a', models.FloatField(default=1, help_text='positive - higher wave variation')),
                ('last_v', models.FloatField(default=0)),
                ('delta_v', models.FloatField(default=0)),
                ('d_delta_v', models.FloatField(default=0)),
                ('ra', models.FloatField(default=0, help_text='higher number more random')),
                ('ce', models.FloatField(default=0, help_text='higher number more centred')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.simulation')),
            ],
        ),
    ]
