# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 18:35
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(help_text='device should publish to mqtt on account_name/deviceID/appID/channelID', max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('channel_desc', models.CharField(blank=True, max_length=50)),
                ('time_tag_year', models.BooleanField(default=False, help_text="tags the channel data with year (eg.'2015')")),
                ('time_tag_month', models.BooleanField(default=False, help_text='tags the channel data with month')),
                ('time_tag_day', models.BooleanField(default=False, help_text='tags the channel data with day of week')),
                ('time_tag_hour', models.BooleanField(default=False, help_text="tags the channel data with hour (eg.'2015')")),
                ('elapsed_since_same_ch', models.BooleanField(default=False, help_text="tags the channel data with seconds since any data was received on SAME channel(eg.cycle time)')")),
                ('elapsed_since_diff_ch', models.BooleanField(default=False, help_text="tags the channel data with seconds since HOOK was received on DIFFERENT channel(for TIME betwen different processes typically RFID')")),
                ('upper_warning', models.FloatField(blank=True)),
                ('lower_warning', models.FloatField(blank=True)),
                ('alarm_logs', models.BooleanField(default=False)),
                ('alarm_email', models.BooleanField(default=False, help_text='alarms will be sent to user who owns device (not active)')),
                ('alarm_raised', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='channel_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('account', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='device should publish to mqtt on account_name/deviceID/appID/channelID', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('device_desc', models.CharField(blank=True, max_length=50)),
                ('group', models.CharField(blank=True, max_length=50)),
                ('subgroup', models.CharField(blank=True, max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, max_length=50)),
                ('install_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='install_date')),
                ('account', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_desc', models.CharField(max_length=50)),
                ('account', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.section'),
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_tags',
            field=models.ManyToManyField(blank=True, to='devices.channel_tag'),
        ),
        migrations.AddField(
            model_name='channel',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
    ]
