# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-08 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='lower_warning',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='upper_warning',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
