# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20170308_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_tags',
            field=models.ManyToManyField(blank=True, to='devices.Channel_tag'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Section'),
        ),
    ]
