# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cert_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(blank=True, max_length=50)),
                ('state_or_province_name', models.CharField(blank=True, max_length=50)),
                ('locality_name', models.CharField(blank=True, max_length=50)),
                ('organization_name', models.CharField(blank=True, max_length=50)),
                ('organization_unit_name', models.CharField(blank=True, max_length=50)),
                ('email_address', models.CharField(blank=True, max_length=50)),
                ('dns_name', models.CharField(blank=True, max_length=250)),
                ('common_name', models.CharField(blank=True, max_length=50)),
                ('dn_qualifier', models.CharField(blank=True, max_length=250)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(blank=True, max_length=50)),
                ('state_or_province_name', models.CharField(blank=True, max_length=50)),
                ('locality_name', models.CharField(blank=True, max_length=50)),
                ('organization_name', models.CharField(blank=True, max_length=50)),
                ('organization_unit_name', models.CharField(blank=True, max_length=50)),
                ('email_address', models.CharField(blank=True, max_length=50)),
                ('dns_name', models.CharField(blank=True, max_length=250)),
                ('common_name', models.CharField(blank=True, max_length=50)),
                ('dn_qualifier', models.CharField(blank=True, max_length=250)),
                ('not_valid_before', models.DateTimeField()),
                ('not_valid_after', models.DateTimeField()),
                ('serial_number', models.CharField(max_length=250)),
                ('revoked', models.BooleanField(default=False)),
                ('account', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
