# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-27 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_pki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert_request',
            name='token',
            field=models.CharField(default='123', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cert_request',
            name='user_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='certificate',
            name='user_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
