# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-27 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_pki', '0002_auto_20170627_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert_request',
            name='issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cert_request',
            name='request_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cert_request',
            name='common_name',
            field=models.CharField(max_length=50),
        ),
    ]
