# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_pki', '0005_certificate_is_ca'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert_request',
            name='is_ca',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cert_request',
            name='token',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='is_ca',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
