# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 05:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_pki', '0006_auto_20170704_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert_request',
            name='not_valid_after',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 3, 5, 28, 17, 99392, tzinfo=utc)),
        ),
    ]
