# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 09:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_pki', '0007_cert_request_not_valid_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert_request',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cert_request',
            name='not_valid_after',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 4, 9, 43, 19, 302113, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
