# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 12:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_pki', '0008_auto_20170706_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert_request',
            name='not_valid_after',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 8, 12, 37, 46, 389078, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cert_request',
            name='token',
            field=models.CharField(db_index=True, default='Y8H8JJGKLGA3AB8YEA6DE07W7PN2X5', max_length=50),
        ),
    ]
