# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 12:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_pki', '0009_auto_20170710_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='issuer_serial_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cert_request',
            name='not_valid_after',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 8, 12, 41, 32, 376843, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cert_request',
            name='token',
            field=models.CharField(db_index=True, default='0O6TZQTVG8RP3SKE1B7GMOXHB3M16S', max_length=50),
        ),
    ]
